### ISSUE TITLE
Suprageneric names treated incorrectly as genus names

### ISSUE THREAD

**Issue by rdmpage** [gbif/iczn-lists#2]
Names that are in ALL CAPS are supra generic names (e.g., tribe, family, etc.) For example, name id 1927 is "Calandraeides" is a tribe, yet field 2 is of type http://rs.tdwg.org/dwc/terms/genus, so  Calandraeides is listed as a genus. Darwin Core lacks an equivalent term to "uninominal" from Roger Hyam's LSID vocabulary http://rs.tdwg.org/ontology/voc/TaxonName.

In fact, I don't see a way to record that a name is, say, a tribe or a subfamily in Darwin Core. I guess "scientificName" but that expects authorship, and I think here we want just the name. IMHO Darwin Core sucks at handling names, it's not set up for nomenclature, instead it assumes we are dealing with taxa, which we aren't.

**Comment by mdoering** [comment]
How about we just use dwc:scientificName and forget about the atomized name parts?
- dwc:scientificName
- dwc:scientificNameAuthorship
- dwc:taxonRank
- dwc:publishedIn
- dwc:publishedInYear

There are also a few 4 parted names in the list, varieties. Right now the species and subspecies epithet live together in specificEpithet which is also wrong. A single name string field might be best...

**Comment by mdoering** [comment]
The latest version uses the full name without authorship in scientificName. I ahve not been able to assign ranks to all names, but many have that now too. Ok to close the issue Rod?

See http://tools.gbif.org/dwca-reports/141-3862897871850342595.html for a preview of the data as of now
