### ISSUE TITLE
Missing authority date for names

### ISSUE THREAD

**Issue by rdmpage** [gbif/iczn-lists#3]
Scientific names have author but not date, e.g _Zosimus_ Schaufuss http://www.gbif.org/species/143328857 should be _Zosimus_ Schaufuss**, 1886**.

**Comment by mdoering** [comment]
A bug in the GBIF checklist bank normalizer code. Fixed here: https://github.com/gbif/checklistbank/commit/8bd97c8d760af4de2c2606cb2846459d070e6670
https://github.com/gbif/checklistbank/commit/a2730583ba67a8a49bdabc517c0d7c5b1237b564

**Comment by rdmpage** [comment]
Thanks, I'll close this.
